### ISSUE TITLE
invalid results for %b in strptime

### ISSUE THREAD

**Issue by JerrySievert** [pineapplemachine/strtime-js#5]
hello,

I'm receiving invalid results using `%b`:

```
strptime('01/Nov/2019:00:04:56 +0000', '%d/%b/%Y:%H:%M:%S %z');
```

the result I'm getting back is for December: `2019-12-01T00:04:56.000Z`

all `Nov` results are returning as December, but other months appear to be working.

any ideas?

thanks!

**Comment by pineapplemachine** [comment]
The failure is more than with just November dates. Almost 50 test cases were failing when I ran them this morning. I think there is a bug in `Date.setUTCMonth` that is occurring because it's New Year's Eve. I will have to further investigate whether this is in fact a bug with `Date.setUTCMonth` or if it's normal behavior that I just haven't come across in documentation before.

I have found a workaround that causes all of the tests to pass again, plus some additional assertions to better cover this particular issue. I will be publishing a new version of the library within the next 30 minutes containing the workaround. You should update your dependency version to v1.1.2.

For a fun time, run this in a repl:

```
[0,1,2,3,4,5,6,7,8,9,10,11].map(i => {
    const t = new Date();
    t.setUTCMonth(i);
    return i + " => " + t.toISOString();
}).join("\n");
```

At the time of writing, this outputs:

```
0 => 2019-01-31T08:16:53.442Z
1 => 2019-03-03T08:16:53.442Z
2 => 2019-03-31T08:16:53.442Z
3 => 2019-05-01T08:16:53.442Z
4 => 2019-05-31T08:16:53.442Z
5 => 2019-07-01T08:16:53.442Z
6 => 2019-07-31T08:16:53.442Z
7 => 2019-08-31T08:16:53.442Z
8 => 2019-10-01T08:16:53.442Z
9 => 2019-10-31T08:16:53.442Z
10 => 2019-12-01T08:16:53.442Z
11 => 2019-12-31T08:16:53.442Z
```

**Comment by pineapplemachine** [comment]
Issue is apparently related to calling `Date.setUTCMonth` with a month containing fewer than 31 days when the Date's UTC day is the 31st.

https://stackoverflow.com/questions/26681313/javascript-setutcmonth-does-not-work-for-november

**Comment by pineapplemachine** [comment]
Closing the issue now as v1.1.2 has been published with a fix. Thank you for catching this!
